ssb_alert_manage service file updated

diff --git a/scripts/ssb_alert_manage b/scripts/ssb_alert_manage
--- a/scripts/ssb_alert_manage
+++ b/scripts/ssb_alert_manage
@@ -21,15 +21,35 @@ COLOR_OK="\\033[0;32m"
 COLOR_WARN="\\033[0;31m"
 COLOR_NORMAL="\\033[0;39m"
 
-#. $ROOT/apps/$ME/etc/profile.d/init.sh
-
 ### ***
+
+if [ ! -d $LOGDIR ]; then 
+  echo "Log Directory '$LOGDIR' does not exists. Creating..."
+  mkdir -p $LOGDIR
+fi
+
+if [ ! -w $LOGDIR ]; then 
+    echo "$USER has no write permission for '$LOGDIR' log directory. Exiting.."
+    exit 1
+fi
+
+## ssb_alert.sh arguments from Environment Variable
+QUERY=$query                                  ## monit influxDB query
+TOKEN=$token                                  ## token file
+URL=${url:-"https://cms-monitoring.cern.ch"}   ## alertmanager_url
+INTERVAL=${interval:-1}                       ## time interval at which fetching and injecting data repeats
+VERBOSE=${verbose:-0}                         ##verbosity level
 
 # Actions Logic
 start()
 {
     echo "Starting Alerting daemon."
-    nohup ssb_alert.sh $query $token </dev/null 2>&1 | rotatelogs $LOGDIR/ssb_alerting-%Y%m%d-`hostname -s`.log 86400 >/dev/null 2>&1 &
+    if [ ! -x "$(command -v rotatelogs)" ]; then
+      echo "rotatelogs not found. Starting without it..."
+      nohup ssb_alert.sh "$QUERY" $TOKEN $URL $INTERVAL $VERBOSE </dev/null 2>&1 &  
+    else
+	    nohup ssb_alert.sh "$QUERY" $TOKEN $URL $INTERVAL $VERBOSE </dev/null 2>&1 | rotatelogs $LOGDIR/ssb_alerting-%Y%m%d-`hostname -s`.log 86400 >/dev/null 2>&1 &
+    fi
 }
 
 stop()
