Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,17 +3,24 @@ name: Continuous integration testing
 on: [pull_request, push]
 
 jobs:
+  test_json:
+    runs-on: ubuntu-latest
+    steps:
+      - run:  echo "Checking valid json..."
 
-  check-json:   
-    - run: |
-      echo "Checking valid json..."
-      #shopt -s globstar
-      #ls **/*.json >/dev/null && for j in **/*.json; do python -mjson.tool "$j" > /dev/null || (echo "INVALID $j" >&2; 1>foo ); done
-      '[[ !  -f "foo" ]]'
+  test_yaml:
+    runs-on: ubuntu-latest
+    steps:
+      - run:  echo "Checking valid yaml..."
 
-  check-yaml:   # This job runs in the test stage.
-    - run: |
-      echo "Checking valid yaml..."
-      #shopt -s globstar
-      #ls **/*.yaml >/dev/null && for j in **/*.yaml; do python -c 'import yaml, sys; print(yaml.safe_load(sys.stdin))' <  $j > /dev/null || (echo "INVALID $j" >&2; 1>foo1 ); done
-      '[[ !  -f "foo1" ]]'
+
+
+  
+#shopt -s globstar
+#ls **/*.json >/dev/null && for j in **/*.json; do python -mjson.tool "$j" > /dev/null || (echo "INVALID $j" >&2; 1>foo ); done
+#      '[[ !  -f "foo" ]]'
+
+
+#      #shopt -s globstar
+#ls **/*.yaml >/dev/null && for j in **/*.yaml; do python -c 'import yaml, sys; print(yaml.safe_load(sys.stdin))' <  $j > /dev/null || (echo "INVALID $j" >&2; 1>foo1 ); done
+#      '[[ !  -f "foo1" ]]'
