Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,16 +27,5 @@ jobs:
         run: |
           echo "Checking valid yaml..."
           shopt -s globstar
-          
-
-
-
-  
-#shopt -s globstar
-#ls **/*.json >/dev/null && for j in **/*.json; do python -mjson.tool "$j" > /dev/null || (echo "INVALID $j" >&2; 1>foo ); done
-#      '[[ !  -f "foo" ]]'
-
-
-#      #shopt -s globstar
-#ls **/*.yaml >/dev/null && for j in **/*.yaml; do python -c 'import yaml, sys; print(yaml.safe_load(sys.stdin))' <  $j > /dev/null || (echo "INVALID $j" >&2; 1>foo1 ); done
-#      '[[ !  -f "foo1" ]]'
+          ls **/*.yaml >/dev/null && for j in **/*.yaml; do python -c 'import yaml, sys; print(yaml.safe_load(sys.stdin))' <  $j > /dev/null || (echo "INVALID $j" >&2; 1>foo1 ); done
+          [[ !  -f "foo1" ]]
